<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="87" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
      <class name="matejonnet.test.TemperatureConverterTest">
        <test-method status="FAIL" signature="arquillianBeforeSuite()" name="arquillianBeforeSuite" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.jboss.arquillian.impl.DeployableTestBuilder.build(DeployableTestBuilder.java:88)
	at org.jboss.arquillian.impl.DeployableTestBuilder.build(DeployableTestBuilder.java:77)
	at org.jboss.arquillian.testng.Arquillian.arquillianBeforeSuite(Arquillian.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:130)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:260)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:995)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:920)
	at org.testng.TestNG.run(TestNG.java:856)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="arquillianBeforeClass()" name="arquillianBeforeClass" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
        </test-method>
        <test-method status="SKIP" signature="arquillianBeforeTest(java.lang.reflect.Method)" name="arquillianBeforeTest" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
        </test-method>
        <test-method status="SKIP" signature="testConvertToCelsius()" name="testConvertToCelsius" duration-ms="7" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
        </test-method>
        <test-method status="FAIL" signature="arquillianAfterTest(java.lang.reflect.Method)" name="arquillianAfterTest" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void matejonnet.test.TemperatureConverterTest.testConvertToCelsius()]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.jboss.arquillian.testng.Arquillian.arquillianAfterTest(Arquillian.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:757)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:995)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:920)
	at org.testng.TestNG.run(TestNG.java:856)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="arquillianBeforeTest(java.lang.reflect.Method)" name="arquillianBeforeTest" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
        </test-method>
        <test-method status="SKIP" signature="testConvertToFarenheit()" name="testConvertToFarenheit" duration-ms="5" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
        </test-method>
        <test-method status="FAIL" signature="arquillianAfterTest(java.lang.reflect.Method)" name="arquillianAfterTest" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void matejonnet.test.TemperatureConverterTest.testConvertToFarenheit()]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.jboss.arquillian.testng.Arquillian.arquillianAfterTest(Arquillian.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:757)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:995)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:920)
	at org.testng.TestNG.run(TestNG.java:856)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="FAIL" signature="arquillianAfterClass()" name="arquillianAfterClass" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.jboss.arquillian.testng.Arquillian.arquillianAfterClass(Arquillian.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:130)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:222)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:995)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:920)
	at org.testng.TestNG.run(TestNG.java:856)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="arquillianAfterSuite()" name="arquillianAfterSuite" is-config="true" duration-ms="0" started-at="2010-12-26T23:22:11Z" finished-at="2010-12-26T23:22:11Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
